<section class="archive-list"> 
    <span class="titleimg">
    <a href="[field:arcurl/]">gong
        <img width="270" height="165" src="[field:picname/]" class="attachment-thumbnail wp-post-image" /></a> </span>
       <div class="mecc">
            <h2 class="mecctitle"> <a href="[field:arcurl/]">[field:title/]</a> </h2>
            <address class="meccaddress">
               <time>[field:pubdate function="MyDate('Y-m-d',@me)"/]</time>
        - 阅[field:click/]
        </address>
                
            <p>[field:description/]......</p>
        </div>
        <div class="clear"></div>
    </section>