<?php
$z[0]=Array("arcurl","",75,90);
$z[0][4]=array();
$z[1]=Array("picname","",141,157);
$z[1][4]=array();
$z[2]=Array("arcurl","",289,304);
$z[2][4]=array();
$z[3]=Array("title","",306,320);
$z[3][4]=array();
$z[4]=Array("pubdate","",396,443);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";
$z[5]=Array("click","",465,479);
$z[5][4]=array();
$z[6]=Array("description","",534,554);
$z[6][4]=array();

?>