<?php
$z[0]=Array("field","",62,85);
$z[0][4]=array();
$z[0][4]['name']="id";
$z[1]=Array("field","",91,119);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",125,154);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel"," \r\n<li><a href=\"[field:typelink/]\">[field:typename/] </a></li>\r\n",202,319);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>