{dede:noteinfo notename="状元笔记-英语" channelid="1" macthtype="string"
refurl="https://www.gaokaotiku.com/forum.php?mod=viewthread&tid=650&extra=page%3D1" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="https://www.gaokaotiku.com/forum.php?mod=forumdisplay&fid=84&page=1"
startid="1" endid="1" addv="1" urlrule="area"
 musthas="mod=viewthread" nothas="tid=8716" listpic="0" usemore="0"}
    {dede:addurls}https://www.gaokaotiku.com/forum.php?mod=forumdisplay&fid=84&page=1{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<ul class="f-content cl">{/dede:areastart}
    {dede:areaend}<span id="fd_page_bottom">{/dede:areaend}
{/dede:listrule}
