<?php
$z[0]=Array("noteinfo","",0,234);
$z[0][4]=array();
$z[0][4]['notename']="状元笔记-英语";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="https://www.gaokaotiku.com/forum.php?mod=viewthread&tid=650&extra=page%3D1";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}https://www.gaokaotiku.com/forum.php?mod=forumdisplay&fid=84&page=1{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<ul class=\"f-content cl\">{/dede:areastart}\r\n    {dede:areaend}<span id=\"fd_page_bottom\">{/dede:areaend}\r\n",238,781);
$z[1][4]=array();
$z[1][4]['sourcetype']="hand";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="https://www.gaokaotiku.com/forum.php?mod=forumdisplay&fid=84&page=1";
$z[1][4]['startid']="1";
$z[1][4]['endid']="1";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="0";
$z[1][4]['usemore']="0";

?>