<?php
$z[0]=Array("addurls","https://www.gaokaotiku.com/forum.php?mod=forumdisplay&fid=84&page=1",6,102);
$z[0][4]=array();
$z[1]=Array("batchrule","",108,141);
$z[1][4]=array();
$z[2]=Array("regxrule","",147,178);
$z[2][4]=array();
$z[3]=Array("areastart","<ul class=\"f-content cl\">",184,242);
$z[3][4]=array();
$z[4]=Array("areaend","<div class=\"bw0 pgs cl mt10\" style=\" margin-top: 20px;\">",248,333);
$z[4][4]=array();

?>