<?php
$z[0]=Array("arcurl","",75,90);
$z[0][4]=array();
$z[1]=Array("picname","",137,153);
$z[1][4]=array();
$z[2]=Array("arcurl","",285,300);
$z[2][4]=array();
$z[3]=Array("title","",302,316);
$z[3][4]=array();
$z[4]=Array("pubdate","",392,439);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";
$z[5]=Array("click","",461,475);
$z[5][4]=array();
$z[6]=Array("description","",530,550);
$z[6][4]=array();

?>