<?php
$z[0]=Array("typelink","",75,92);
$z[0][4]=array();
$z[1]=Array("picname","",139,155);
$z[1][4]=array();
$z[2]=Array("arcurl","",287,302);
$z[2][4]=array();
$z[3]=Array("title","",304,318);
$z[3][4]=array();
$z[4]=Array("pubdate","",394,441);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";
$z[5]=Array("click","",463,477);
$z[5][4]=array();
$z[6]=Array("description","",532,552);
$z[6][4]=array();

?>