<section class="list">
    <span class="titleimg">
    <a href="[field:arcurl/]">
        <img width="270" height="165" src="[field:picname/]" class="attachment-thumbnail wp-post-image" /></a>
         </span>
        
        <a href="[field:arcurl/]" class="up" ></a>
		      <div class="mecc">
            <h2 class="mecctitle">
            
             <a href="[field:arcurl/]">[field:title/]</a> </h2>
            <address class="meccaddress">
                <time>[field:pubdate function="MyDate('y年m月d日',@me)"/]</time>
                <img src="/skin/Picture/n.png">
                <a href='/[field:typeurl/]'>[field:typename/]</a> -
                阅[field:click/]</address>
            <p>[field:info/]...<a href="[field:arcurl/]">[查看全文]</a></p>
        </div>
        <div class="clear"></div>

    </section>