<?php
$z[0]=Array("typelink","",75,92);
$z[0][4]=array();
$z[1]=Array("picname","",143,159);
$z[1][4]=array();
$z[2]=Array("arcurl","",291,306);
$z[2][4]=array();
$z[3]=Array("title","",308,322);
$z[3][4]=array();
$z[4]=Array("pubdate","",398,445);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";
$z[5]=Array("click","",467,481);
$z[5][4]=array();
$z[6]=Array("description","",536,556);
$z[6][4]=array();

?>