<?php
$z[0]=Array("global","",113,138);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",148,174);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",226,256);
$z[2][4]=array();
$z[2][4]['name']="cfg_description";
$z[3]=Array("type","\r\n            <li class=\"menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home\"><a href=\"[field:typelink/]/\">[field:typename/]</a></li>\r\n            ",472,709);
$z[3][4]=array();
$z[3][4]['typeid']="51";
$z[4]=Array("channel","\r\n			<li class=\"menu-item menu-item-type-taxonomy menu-item-object-category\"><a title=\"[field:typename/]\" href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            ",756,982);
$z[4][4]=array();
$z[4][4]['row']="6";
$z[4][4]['type']="top";

?>