<?php
$z[0]=Array("global","",212,238);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",282,312);
$z[1][4]=array();
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",349,376);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",915,950);
$z[3][4]=array();
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n\r\n    <section class=\"list\">\r\n    <span class=\"titleimg\">\r\n    <a href=\"[field:arcurl/]\">\r\n        <img width=\"270\" height=\"165\" src=\"[field:picname/]\" class=\"attachment-thumbnail wp-post-image\" /></a>\r\n         </span>\r\n        \r\n        <a href=\"[field:arcurl/]\" class=\"up\" ></a>\r\n		      <div class=\"mecc\">\r\n            <h2 class=\"mecctitle\">\r\n            \r\n             <a href=\"[field:arcurl/]\">[field:title/]</a> </h2>\r\n            <address class=\"meccaddress\">\r\n                <time>[field:pubdate function=\"MyDate('20y年m月d日',@me)\"/]</time>\r\n                <img src=\"/skin/Picture/n.png\">\r\n                <a href='[field:typeurl/]'>[field:typename/]</a> -\r\n                阅[field:click/]</address>\r\n            <p>[field:info/]...<a href=\"[field:arcurl/]\">[查看全文]</a></p>\r\n        </div>\r\n        <div class=\"clear\"></div>\r\n\r\n    </section>\r\n  ",1348,2298);
$z[4][4]=array();
$z[4][4]['typeid']="1";
$z[4][4]['row']="6";
$z[4][4]['titlelen']="80";
$z[4][4]['infolen']="200";
$z[5]=Array("arclist","\r\n\r\n    <section class=\"list\">\r\n    <span class=\"titleimg\">\r\n    <a href=\"[field:arcurl/]\">\r\n        <img width=\"270\" height=\"165\" src=\"[field:picname/]\" class=\"attachment-thumbnail wp-post-image\" /></a>\r\n         </span>\r\n        \r\n        <a href=\"[field:arcurl/]\" class=\"up\" ></a>\r\n		      <div class=\"mecc\">\r\n            <h2 class=\"mecctitle\">\r\n            \r\n             <a href=\"[field:arcurl/]\">[field:title/]</a> </h2>\r\n            <address class=\"meccaddress\">\r\n                <time>[field:pubdate function=\"MyDate('20y年m月d日',@me)\"/]</time>\r\n                <img src=\"/skin/Picture/n.png\">\r\n                <a href='/[field:typeurl/]'>[field:typename/]</a> -\r\n                阅[field:click/]</address>\r\n            <p>[field:info/]...<a href=\"[field:arcurl/]\">[查看全文]</a></p>\r\n        </div>\r\n        <div class=\"clear\"></div>\r\n\r\n    </section>\r\n  ",2302,3254);
$z[5][4]=array();
$z[5][4]['typeid']="14";
$z[5][4]['row']="6";
$z[5][4]['titlelen']="80";
$z[5][4]['infolen']="200";
$z[6]=Array("arclist","\r\n\r\n    <section class=\"list\">\r\n    <span class=\"titleimg\">\r\n    <a href=\"[field:arcurl/]\">\r\n        <img width=\"270\" height=\"165\" src=\"[field:picname/]\" class=\"attachment-thumbnail wp-post-image\" /></a>\r\n         </span>\r\n        \r\n        <a href=\"[field:arcurl/]\" class=\"up\" ></a>\r\n		      <div class=\"mecc\">\r\n            <h2 class=\"mecctitle\">\r\n            \r\n             <a href=\"[field:arcurl/]\">[field:title/]</a> </h2>\r\n            <address class=\"meccaddress\">\r\n                <time>[field:pubdate function=\"MyDate('20y年m月d日',@me)\"/]</time>\r\n                <img src=\"/skin/Picture/n.png\">\r\n                <a href='/[field:typeurl/]'>[field:typename/]</a> -\r\n                阅[field:click/]</address>\r\n            <p>[field:info/]...<a href=\"[field:arcurl/]\">[查看全文]</a></p>\r\n        </div>\r\n        <div class=\"clear\"></div>\r\n\r\n    </section>\r\n  ",3258,4211);
$z[6][4]=array();
$z[6][4]['typeid']="51";
$z[6][4]['row']="10";
$z[6][4]['titlelen']="80";
$z[6][4]['infolen']="200";
$z[7]=Array("include","",4316,4352);
$z[7][4]=array();
$z[7][4]['filename']="right.htm";
$z[8]=Array("include","",4419,4456);
$z[8][4]=array();
$z[8][4]['filename']="footer.htm";

?>