<?php
$z[0]=Array("tag","\r\n                    <li class=\"menu-item menu-item-type-custom menu-item-object-custom\"><a href=\"[field:link/]\">[field:tag /]</a></li>\r\n                        ",432,639);
$z[0][4]=array();
$z[0][4]['sort']="month";
$z[0][4]['row']="15";
$z[1]=Array("channelartlist"," \r\n    <div class=\"sitebar_list\">\r\n        <h4 class=\"sitebar_title\"><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></h4>\r\n        <ul class=\"sitebar_list_ul\">\r\n{dede:channel type='son' noself='yes'} \r\n<li><a href=\"[field:typelink/]\">[field:typename/] </a></li>\r\n{/dede:channel} \r\n        </ul>\r\n    </div>\r\n\r\n",753,1152);
$z[1][4]=array();
$z[1][4]['typeid']="top";
$z[1][4]['row']="8";
$z[2]=Array("arclist","\r\n      \r\n<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n",1292,1440);
$z[2][4]=array();
$z[2][4]['orderby']="pubdate";
$z[2][4]['flag']="c";
$z[2][4]['titlelen']="42";
$z[2][4]['row']="5";
$z[3]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n   ",1607,1735);
$z[3][4]=array();
$z[3][4]['orderby']="click";
$z[3][4]['titlelen']="42";
$z[3][4]['row']="5";

?>